In [ ]:
import numpy as np
import os

import scipy.sparse as sp
import os
import tensorflow as tf
!pip install spektral
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import categorical_accuracy
from tensorflow.keras.models import Model
import math
from tensorflow.keras.optimizers import Adam

from spektral.data import Dataset, DisjointLoader, Graph
from spektral.layers import GCSConv, GlobalAvgPool
from spektral.transforms.normalize_adj import NormalizeAdj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 140 kB 5.0 MB/s 


Loading files sequentially

In [ ]:
path_of_the_directory = '/content/drive/MyDrive/reaxff/xmolout'
ext = ('')
for files in sorted(os.listdir(path_of_the_directory)): #now sequential
    if files.endswith(ext):
        print(files)
        f2 = files  
    else:
        continue
#print(len(files))



xmolout_001
xmolout_002
xmolout_003
xmolout_004
xmolout_005
xmolout_006
xmolout_007
xmolout_008
xmolout_009
xmolout_010
xmolout_011
xmolout_012
xmolout_013
xmolout_014
xmolout_015
xmolout_016
xmolout_017
xmolout_018
xmolout_019
xmolout_020
xmolout_021
xmolout_022
xmolout_023
xmolout_024
xmolout_025
xmolout_026
xmolout_027
xmolout_028
xmolout_029
xmolout_030
xmolout_031
xmolout_032
xmolout_033
xmolout_034
xmolout_035
xmolout_036
xmolout_037
xmolout_038
xmolout_039
xmolout_040
xmolout_041
xmolout_042
xmolout_043
xmolout_044
xmolout_045
xmolout_046
xmolout_047
xmolout_048
xmolout_049
xmolout_050
xmolout_051
xmolout_052
xmolout_053
xmolout_054
xmolout_055
xmolout_056
xmolout_057
xmolout_058
xmolout_059
xmolout_060
xmolout_061
xmolout_062
xmolout_063
xmolout_064
xmolout_065
xmolout_066
xmolout_067
xmolout_068
xmolout_069
xmolout_070
xmolout_071
xmolout_072
xmolout_073
xmolout_074
xmolout_075
xmolout_076
xmolout_077
xmolout_078
xmolout_079
xmolout_080
xmolout_081
xmolout_082
xmolout_083
xmol

In [ ]:
def remove(string):
    return string.replace(" ", "")

def distance_iter_mat(x, d_min, d_max, a1_index, a2_index):

  #a1 index = line no of 1st atom in xmolout
  #a2 index = line no of 2nd atom in xmolout
  
  x_a1 = np.zeros(math.ceil(len(x)/76))
  y_a1 = np.zeros(math.ceil(len(x)/76))
  z_a1 = np.zeros(math.ceil(len(x)/76))
  x_a2 = np.zeros(math.ceil(len(x)/76))
  y_a2 = np.zeros(math.ceil(len(x)/76))
  z_a2 = np.zeros(math.ceil(len(x)/76))


  for i_x in range (0, math.floor(len(x)/76)):
  #print(i_x)
  #print(x[9+76*i_x])
  #print(x[9+76*i_x][4:12]) 
    x_a1[i_x] = float(x[a1_index+76*i_x][4:12])
    x_a2[i_x] = float(x[a2_index+76*i_x][4:12])

  for i_y in range (0, math.floor(len(x)/76)):
  #print(i_y)
  #print(x[9+76*i_y])
  #print(x[9+76*i_y][13:21]) 
    y_a1[i_y] = float(x[a1_index+76*i_y][13:21])
    y_a2[i_y] = float(x[a2_index+76*i_y][13:21])
  for i_z in range (0, math.floor(len(x)/76)):
  
  
  #print(x[9+76*i_z][13:21]) 
    z_a1[i_z] = float(x[a1_index+76*i_z][22:31])
    z_a2[i_z] = float(x[a2_index+76*i_z][22:31])




    x_diff = np.square(x_a1-x_a2)
    y_diff = np.square(y_a1-y_a2)
    z_diff = np.square(z_a1-z_a2)
    dist_a1_a2 = np.sqrt(x_diff + y_diff + z_diff)

  #print(dist_a1_a2)

  res_a1_a2 = np.where(np.logical_and(dist_a1_a2 >= d_min, dist_a1_a2 <= d_max))
  #print(res_a1_a2)
  print(type(res_a1_a2))
  return res_a1_a2#, dist_a1_a2

  #for i_ts in res_c1_n1:
    #print(i_ts)
    #print(dist_a1_a2[i_ts])



def common_member(a, b):
    a_set = set(a)
    b_set = set(b)
 
    if (a_set & b_set):
        print(a_set & b_set)
    else:
        print("No common elements")

def distance_check(dist_matrix, d_min, d_max): #not checking others as they are molecules themselves
 

  #dist_matrix -> the matrix calculated by dist function above
  c1_line = 59 #line nummer in xmolout counting from 0 onwards
  n1_line = 9
  o1_line = 60
  h1_line_1 = 20  #both h connected to n can react
  h1_line_2 = 21
  x_r = np.zeros(100,15,100)
  for i_dm in range(0, len(dist_matrix)):
    x_r = np.where(np.logical_and(dist_matrix >= d_min, dist_matrix <= d_max))
  
def contains(tuple, given_char):
    if given_char in tuple:
        print(given_char)
        return True
    return False   
  

def common(a,b): 
  c = [value for value in a if value in b] 
  return c

    

In [ ]:
path_of_the_directory_2 = '/content/drive/MyDrive/reaxff/tracking'
ext = ('')

trk_files = sorted(os.listdir(path_of_the_directory_2))
print(trk_files)

path_of_the_directory_3 = '/content/drive/MyDrive/reaxff/molfra'

molfras = sorted(os.listdir(path_of_the_directory_3))
print(molfras)

['tracking.in_001', 'tracking.in_002', 'tracking.in_003', 'tracking.in_004', 'tracking.in_005', 'tracking.in_006', 'tracking.in_007', 'tracking.in_008', 'tracking.in_009', 'tracking.in_010', 'tracking.in_011', 'tracking.in_012', 'tracking.in_013', 'tracking.in_014', 'tracking.in_015', 'tracking.in_016', 'tracking.in_017', 'tracking.in_018', 'tracking.in_019', 'tracking.in_020', 'tracking.in_021', 'tracking.in_022', 'tracking.in_023', 'tracking.in_024', 'tracking.in_025', 'tracking.in_026', 'tracking.in_027', 'tracking.in_028', 'tracking.in_029', 'tracking.in_030', 'tracking.in_031', 'tracking.in_032', 'tracking.in_033', 'tracking.in_034', 'tracking.in_035', 'tracking.in_036', 'tracking.in_037', 'tracking.in_038', 'tracking.in_039', 'tracking.in_040', 'tracking.in_041', 'tracking.in_042', 'tracking.in_043', 'tracking.in_044', 'tracking.in_045', 'tracking.in_046', 'tracking.in_047', 'tracking.in_048', 'tracking.in_049', 'tracking.in_050', 'tracking.in_051', 'tracking.in_052', 'tracking.i

In [ ]:
for files in sorted(os.listdir(path_of_the_directory)): #now sequential
  i_track = 0
  path = '/content/drive/MyDrive/reaxff/xmolout' + '/' + files
  fp = open(path, 'r')
  x = fp.readlines()
  print(x[9])
  path_tk = '/content/drive/MyDrive/reaxff/tracking' + '/' + trk_files[i_track]
  i_track = i_track + 1
  ft = open(path_tk, 'r')
  track = ft.readlines()
  #print(track)
  path_mol = '/content/drive/MyDrive/reaxff/molfra' + '/' + molfras[i_track]
  fm = open(path_mol, 'r')
  molf = fm.readlines()

  r1 = list(distance_iter_mat(x, 3, 12, 9, 59))
#9 is for n1 and 59 for c1
# n1 - 10th - 9 in xmolout
# c1 - 58 - 59
# h1 - 20/21 - 19/20
# o1 - 59 - 60
#numbering in xmolout starts from zero
  #print((track[2][41:45]))
  #print(track[2][49:54])


#  distance_iter_mat(x,float(remove(track[2][41:45])), float(remove(track[2][49:54])), 60, 61)  #o1 and c1
  
  #print(type(intersection_1))
  #print(x[28])
  r2 = list(distance_iter_mat(x, float(remove(track[2][65:69])), float(remove(track[2][70:75])), 28, 60))   #h1 and o1
  print('r1/r2', r1,r2)

  for r1_e in r1[0]:
    for r2_e in r2[0]:
      if r1_e == r2_e:
        print('intersection of nc and oh', r1_e, r2_e)
  #index_of_mofra_rxn = molf[i_track]
  #print(molf)


  mylist = ['abc123', 'def456', 'ghi789']
  sub = '178.1440'
  next((s for s in molf if sub in s), None) # returns 'abc123'

N    8.32447   0.26538   3.83790     1        -74.96943

<class 'tuple'>
<class 'tuple'>
r1/r2 [array([0, 1, 2, 3, 4, 5, 6, 7, 8])] [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])]
intersection of nc and oh 0 0
intersection of nc and oh 1 1
intersection of nc and oh 2 2
intersection of nc and oh 3 3
intersection of nc and oh 4 4
intersection of nc and oh 5 5
intersection of nc and oh 6 6
intersection of nc and oh 7 7
intersection of nc and oh 8 8
N    8.19327  14.32520  12.20414     1        -74.34023

<class 'tuple'>
<class 'tuple'>
r1/r2 [array([1, 2, 3, 4])] [array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11])]
intersection of nc and oh 1 1
intersection of nc and oh 2 2
intersection of nc and oh 3 3
intersection of nc and oh 4 4
N   14.41465  11.82444  10.70484     1        -74.78538

<class 'tuple'>
<class 'tuple'>
r1/r2 [array([0, 1, 2, 3, 4, 5, 6, 7, 8])] [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])]
intersection of nc 

In [ ]:
#Printing what kind of reaction happens in each of the cases using their molfra file
#127 reactions total 

Reac_outcome = np.zeros((1,500))
i_reac = 1
for files_m in sorted(os.listdir('/content/drive/MyDrive/reaxff/molfra')):
  path_m = '/content/drive/MyDrive/reaxff/molfra' + '/' + files_m
  fm = open(path_m, 'r')
  x_mo = fm.readlines()
  #print('len = ', len(x_mo))
  for i_xmo in range(3,4):#len(x_mo))):
    print(files_m)
    print(i_reac)

    #print(x_mo[len(x_mo)-3][27:])
    if int(remove((x_mo[len(x_mo)-3][27:]))) > 2:
      print(files_m, 'Rxn happened, stuff broken down')
      Reac_outcome[0][i_reac] = 1
    elif int(remove((x_mo[len(x_mo)-3][27:]))) == 1:
      print(files_m, 'Rxn happened, molecules joined')
      Reac_outcome[0][i_reac] = 1
    elif int(remove((x_mo[len(x_mo)-3][27:]))) == 2:
      #print(x_mo[2])
      #print(x_mo[len(x_mo)-5])
      if (x_mo[2][10:]) == (x_mo[len(x_mo)-5][10:]):
        print(files_m, 'No Rxn')
      else:
        print('Miscellaneous Rxn') 
    i_reac = i_reac + 1


molfra.out_001
1
molfra.out_001 Rxn happened, molecules joined
molfra.out_002
2
molfra.out_002 No Rxn
molfra.out_003
3
molfra.out_003 No Rxn
molfra.out_004
4
molfra.out_004 Rxn happened, molecules joined
molfra.out_005
5
molfra.out_005 Rxn happened, molecules joined
molfra.out_006
6
molfra.out_006 Rxn happened, molecules joined
molfra.out_007
7
molfra.out_007 No Rxn
molfra.out_008
8
Miscellaneous Rxn
molfra.out_009
9
molfra.out_009 No Rxn
molfra.out_010
10
molfra.out_010 No Rxn
molfra.out_011
11
molfra.out_011 No Rxn
molfra.out_012
12
Miscellaneous Rxn
molfra.out_013
13
molfra.out_013 No Rxn
molfra.out_014
14
molfra.out_014 No Rxn
molfra.out_015
15
molfra.out_015 No Rxn
molfra.out_016
16
molfra.out_016 No Rxn
molfra.out_017
17
molfra.out_017 Rxn happened, molecules joined
molfra.out_018
18
molfra.out_018 No Rxn
molfra.out_019
19
molfra.out_019 No Rxn
molfra.out_020
20
molfra.out_020 No Rxn
molfra.out_021
21
molfra.out_021 No Rxn
molfra.out_022
22
molfra.out_022 No Rxn
molfra.out_023
23

In [ ]:
print(Reac_outcome)

[[0. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.
  0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.
  0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 

In [ ]:
# Reading the connectivity matrix (fort.7)

def read_con(path_fort_7):
#path_fort_7 = '/content/fort.7'
  f7 = open(path_fort_7, 'r')
  x_f7 = f7.readlines()
  #print(len(x_f7))
  cm_1 = np.zeros((76,76))
  #print(len(x_f7))
  for i_7 in range(1,len(x_f7)-2):
    for i_7_1 in range(1,7):
      #print(x_f7[i_7][5*i_7_1-2:5*i_7_1+2])
      cm_1[i_7][i_7_1] = bool(remove(x_f7[i_7][5*i_7_1-2:5*i_7_1+2]))
      cm_1[i_7_1][i_7] = bool(remove(x_f7[i_7][5*i_7_1-2:5*i_7_1+2]))


  np.savetxt("foo.csv", cm_1, delimiter=",")
  return cm_1

In [ ]:
# Reading node attributes (atom types) from the geo file

def read_attr(path_geo):  # read only even numbered geo files

#path_geo = '/content/geo'
  fg = open(path_geo, 'r')
  x_fg = fg.readlines()
  #print(x_fg)
  print(x_fg[14]) #->N_a2
  print(x_fg[65])  #->O_a1
  print(x_fg[64]) #->C_a1
  print(x_fg[63]) #->C_a1
  print(x_fg[26]) #->H_a2
  print(x_fg[27]) #->H_a2

  #INPUT PROCESSING
  def input_proces(atom_id, path_geo):
    fg = open(path_geo, 'r')
    x_fg = fg.readlines()
    inp1 = np.zeros((1,4))
    inp1[0][0] = ord(x_fg[atom_id][13])#atom 
    inp1[0][1] = float(remove(x_fg[atom_id][30:41])) # x-coord
    inp1[0][2] = float(remove(x_fg[atom_id][41:52]))
    inp1[0][3] = float(remove(x_fg[atom_id][52:61]))
    print(inp1)
    return(inp1)

  #print(x_fg[7][13])

  node_mat = np.zeros((74,2))
  #print(len(x_fg))
  for i_8 in range(7,80):
    #for i_8_1 in range(1,7):
      #print(x_f7[i_7][5*i_7_1-2:5*i_7_1+2])
    #print(i_8-7)
    node_mat[i_8-7][1] = ord(x_fg[i_8][13])
    


  #np.savetxt("nodes.csv", node_mat, delimiter=",")
  return(node_mat)

In [ ]:
def input_proces(atom_id, path_geo):
  fg = open(path_geo, 'r')
  x_fg = fg.readlines()
  inp1 = np.zeros((1,4))
  inp1[0][0] = ord(x_fg[atom_id][13])#atom 
  inp1[0][1] = float(remove(x_fg[atom_id][30:41])) # x-coord
  inp1[0][2] = float(remove(x_fg[atom_id][41:52]))
  inp1[0][3] = float(remove(x_fg[atom_id][52:61]))
  print(inp1)
  return(inp1)

In [ ]:
#read_attr('/content/drive/MyDrive/reaxff/geo/geo_002')
geo_files = sorted(os.listdir('/content/drive/MyDrive/reaxff/geo'))
print(geo_files)

mol_1_attr = np.zeros((500, 3, 4))
mol_2_attr = np.zeros((500, 3, 4))

for i_g in range(1,500):
  #if 2*i_g%2 == 1:
   # 2*i_g = 2*i_g - 1

  path_geo_even = geo_files[2*i_g]
  #print(i_g, 2*i_g, path_geo_even)
  #mol_1_attr = np.zeros((3,4))
  for atom_id in [63,64,65]:#,14,26,27]:
    path_geo_even = '/content/drive/MyDrive/reaxff/geo' + '/' + geo_files[2*i_g]
    print(path_geo_even)
    mol_1_attr[i_g][atom_id-63] = input_proces(atom_id, path_geo_even)#'/content/drive/MyDrive/reaxff/geo/geo_002')

  #mol_2_attr = np.zeros((3,4))
  i_1 = 0
  for atom_id in [14,26,27]:
    
    path_geo_even = '/content/drive/MyDrive/reaxff/geo' + '/' + geo_files[2*i_g]
    print(path_geo_even)
    mol_2_attr[i_g][i_1] = input_proces(atom_id, path_geo_even)#'/content/drive/MyDrive/reaxff/geo/geo_002')
    i_1 = i_1 + 1

Streaming output truncated to the last 5000 lines.
/content/drive/MyDrive/reaxff/geo/geo_166
[[79.      14.42949 20.87827 10.15194]]
/content/drive/MyDrive/reaxff/geo/geo_166
[[78.      11.34699 12.49964  9.66113]]
/content/drive/MyDrive/reaxff/geo/geo_166
[[72.      12.36067 12.63174  9.6715 ]]
/content/drive/MyDrive/reaxff/geo/geo_166
[[72.      10.82901 13.3665   9.50577]]
/content/drive/MyDrive/reaxff/geo/geo_168
[[67.      -0.28873  3.08247  7.21627]]
/content/drive/MyDrive/reaxff/geo/geo_168
[[ 6.70000e+01 -1.45600e-02  3.58623e+00  8.58212e+00]]
/content/drive/MyDrive/reaxff/geo/geo_168
[[79.      -1.31189  3.21872  8.17584]]
/content/drive/MyDrive/reaxff/geo/geo_168
[[78.      11.34699 12.49964  9.66113]]
/content/drive/MyDrive/reaxff/geo/geo_168
[[72.      12.36067 12.63174  9.6715 ]]
/content/drive/MyDrive/reaxff/geo/geo_168
[[72.      10.82901 13.3665   9.50577]]
/content/drive/MyDrive/reaxff/geo/geo_170
[[67.       3.79038  6.79243 14.44832]]
/content/drive/MyDrive/reaxff/g

In [ ]:
print(mol_1_attr)


[[[ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]]

 [[67.       9.04602  5.72952 16.39124]
  [67.       7.80473  5.14068 16.94526]
  [79.       8.77968  5.72713 17.77517]]

 [[67.       7.4314   0.44142  1.72934]
  [67.       6.69779  1.07713  2.84835]
  [79.       6.28321  1.22896  1.51109]]

 ...

 [[67.       3.10641 12.23937  5.79308]
  [67.       3.6771  10.95164  6.25195]
  [79.       2.42503 11.01923  5.61089]]

 [[67.      -0.5677  11.97562 11.48542]
  [67.      -0.61699 10.53053 11.80756]
  [79.      -1.75776 11.35013 11.90815]]

 [[67.      14.35782 15.22281  3.78584]
  [67.      14.14682 14.38603  4.98991]
  [79.      13.08533 15.07646  4.37368]]]


In [ ]:
print(mol_2_attr)

[[[ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]]

 [[78.      11.34699 12.49964  9.66113]
  [72.      12.36067 12.63174  9.6715 ]
  [72.      10.82901 13.3665   9.50577]]

 [[78.      11.34699 12.49964  9.66113]
  [72.      12.36067 12.63174  9.6715 ]
  [72.      10.82901 13.3665   9.50577]]

 ...

 [[78.      11.34699 12.49964  9.66113]
  [72.      12.36067 12.63174  9.6715 ]
  [72.      10.82901 13.3665   9.50577]]

 [[78.      11.34699 12.49964  9.66113]
  [72.      12.36067 12.63174  9.6715 ]
  [72.      10.82901 13.3665   9.50577]]

 [[78.      11.34699 12.49964  9.66113]
  [72.      12.36067 12.63174  9.6715 ]
  [72.      10.82901 13.3665   9.50577]]]


In [ ]:
#CONSTANT CONNECTIVITY MATRIX (from slide 10)

conn_mat_1 = [[0,1,1],[1,0,0],[1,0,0]] #nh2
conn_mat_2 = [[0,1,1],[1,0,1],[1,1,0]] #cco


In [ ]:
# NOW CREATING GRAPH
import spektral
mol1 = spektral.data.Graph

mol1.a = conn_mat_1
mol1.x = mol_1_attr
mol1.y = 1

Graph()

Graph(n_nodes=None, n_node_features=None, n_edge_features=None, n_labels=None)

In [ ]:
# Graph creating function

def Create_graph(graph_id, i_graph, output):
  #for i in range(100):
  graph_id = spektral.data.Graph
  graph_id.x = mol_1_attr[i_graph] #rand(self.nodes, self.feats)
  print('x done')
  graph_id.a = [[0,1,1],[1,0,0],[1,0,0]]#conn_mat_1 #randint(0, 2, (self.nodes, self.nodes))
  print('a done')
  graph_id.y = Reac_outcome[0][i_graph] #randint(0, 2)
  print('y done')
  output.append(graph_id)
  print(graph_id)
            #Graph(x=mol_1_attr[i_graph], a=[[0,1,1],[1,0,0],[1,0,0]], y=Reac_outcome[0][i_graph]))
  #filename = os.path.join('/content/sample_data/Output', f'graph_{i_graph}')
  #np.savez(filename, x=x, a=a, y=y)
             
  #return Graph(x=graph_id.x, a=graph_id.a, y=graph_id.y)

In [ ]:
#mol_test = spektral.data.Graph
graph_id = 'mol_test'
Create_graph(graph_id, 4, [])

x done
a done
y done
<class 'spektral.data.graph.Graph'>


In [ ]:
var_holder = []#np.zeros((1,100))#{}
op = [] 


for i in range(1,100):
    #var_holder['graph_id_' + str(i)] = 'mol_' + i
    print(i)
    temp_name_holder = 'mol_' + str(i)
    print(temp_name_holder)
    var_holder.append(temp_name_holder) #= 'mol_' + str(i)
    op.append(Create_graph(temp_name_holder, i, []))
    
    #Create_graph(i,i)
    
#locals().update(var_holder)
#print(graph_id_54)
print(var_holder)

1
mol_1
x done
a done
y done
<class 'spektral.data.graph.Graph'>
2
mol_2
x done
a done
y done
<class 'spektral.data.graph.Graph'>
3
mol_3
x done
a done
y done
<class 'spektral.data.graph.Graph'>
4
mol_4
x done
a done
y done
<class 'spektral.data.graph.Graph'>
5
mol_5
x done
a done
y done
<class 'spektral.data.graph.Graph'>
6
mol_6
x done
a done
y done
<class 'spektral.data.graph.Graph'>
7
mol_7
x done
a done
y done
<class 'spektral.data.graph.Graph'>
8
mol_8
x done
a done
y done
<class 'spektral.data.graph.Graph'>
9
mol_9
x done
a done
y done
<class 'spektral.data.graph.Graph'>
10
mol_10
x done
a done
y done
<class 'spektral.data.graph.Graph'>
11
mol_11
x done
a done
y done
<class 'spektral.data.graph.Graph'>
12
mol_12
x done
a done
y done
<class 'spektral.data.graph.Graph'>
13
mol_13
x done
a done
y done
<class 'spektral.data.graph.Graph'>
14
mol_14
x done
a done
y done
<class 'spektral.data.graph.Graph'>
15
mol_15
x done
a done
y done
<class 'spektral.data.graph.Graph'>
16
mol_16
x d

In [ ]:
print(op)

[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]


In [ ]:
class MyDataset(Dataset):
    
    def __init__(self, nodes, feats, **kwargs):
        self.nodes = nodes
        self.feats = feats
        print('run1')
        super().__init__(**kwargs)


    # Create the directory
        print(self.path)
      #os.mkdir('/content/sample_data/custom_dataset' + str(self))

    # Write the data to file
        for i0 in range(0,249):
          x = mol_1_attr[i0]
          print(mol_1_attr[i0])
          a = [[0,1,1],[1,0,0],[1,0,0]]
          y = 1
          print('run2')
          filename = os.path.join('/content/sample_data/Output', f'graph_{i0}')
          np.savez(filename, x=x, a=a, y=y)

    def read(self):
    # We must return a list of Graph objects
      output = []

      for i01 in range(0,249):
        data = np.load(os.path.join('/content/sample_data/Output', f'graph_{i01}.npz'))
        output.append(
            Graph(x=data['x'], a=data['a'], y=data['y'])
        )

      return output

In [ ]:
for i0 in range(0,250):
          x = mol_1_attr[i0]
          print(mol_1_attr[i0])
          a = [[0,1,1],[1,0,0],[1,0,0]]
          y = 1
          print('run2')
          filename = os.path.join('/content/sample_data/Output', f'graph_{i0}')
          np.savez(filename, x=x, a=a, y=y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
run2
[[67.       9.04602  5.72952 16.39124]
 [67.       7.80473  5.14068 16.94526]
 [79.       8.77968  5.72713 17.77517]]
run2
[[67.       7.4314   0.44142  1.72934]
 [67.       6.69779  1.07713  2.84835]
 [79.       6.28321  1.22896  1.51109]]
run2
[[67.       5.2962   6.22972  2.53243]
 [67.       6.07721  6.8305   3.63859]
 [79.       6.05684  5.43982  3.41769]]
run2
[[67.       4.56899 12.69411 17.77566]
 [67.       3.14911 12.50895 18.15536]
 [79.       4.06808 13.14179 19.01455]]
run2
[[67.      19.17142  9.10437  1.64582]
 [67.      18.78649  9.0185   3.07374]
 [79.      18.64142  7.92256  2.20134]]
run2
[[67.      20.21404 11.94374  9.55411]
 [67.      20.62679 10.5394   9.78204]
 [79.      19.3506  10.8635   9.28256]]
run2
[[67.       6.08347 15.19488 14.50082]
 [67.       6.64574 13.84666 14.25453]
 [79.       5.63189 14.06244 15.20782]]
run2
[[67.      11.03944  4.94518 17.65783]
 [67.      10.88988  4.91682 19.13137]
 [79.     

In [ ]:
    # We must return a list of Graph objects
output = []

for i in range(0,249):
  data = np.load(os.path.join('/content/sample_data/Output', f'graph_{i}.npz'))
  output.append(
  Graph(x=data['x'], a=data['a'], y=data['y'])
  )

print(output)

[Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1), Graph

In [ ]:
#os.mkdir('/root/spektral/datasets/MyDataset')
dataset = MyDataset(3, 3)
print(dataset)
#for i_dt in range(1,2):
#  print(dataset[i_dt])


run1
/root/spektral/datasets/MyDataset
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
run2
[[67.       9.04602  5.72952 16.39124]
 [67.       7.80473  5.14068 16.94526]
 [79.       8.77968  5.72713 17.77517]]
run2
[[67.       7.4314   0.44142  1.72934]
 [67.       6.69779  1.07713  2.84835]
 [79.       6.28321  1.22896  1.51109]]
run2
[[67.       5.2962   6.22972  2.53243]
 [67.       6.07721  6.8305   3.63859]
 [79.       6.05684  5.43982  3.41769]]
run2
[[67.       4.56899 12.69411 17.77566]
 [67.       3.14911 12.50895 18.15536]
 [79.       4.06808 13.14179 19.01455]]
run2
[[67.      19.17142  9.10437  1.64582]
 [67.      18.78649  9.0185   3.07374]
 [79.      18.64142  7.92256  2.20134]]
run2
[[67.      20.21404 11.94374  9.55411]
 [67.      20.62679 10.5394   9.78204]
 [79.      19.3506  10.8635   9.28256]]
run2
[[67.       6.08347 15.19488 14.50082]
 [67.       6.64574 13.84666 14.25453]
 [79.       5.63189 14.06244 15.20782]]
run2
[[67.      11.03944  4.94518 17.65783]
 [67.     

The role of a Loader is to iterate over a Dataset and yield batches of graphs to feed your Keras Models.

This is achieved by having a generator object that produces lists of Graphs, which are then collated together and returned as Tensors.

In [ ]:
import numpy as np
import scipy.sparse as sp
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import categorical_accuracy
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

from spektral.data import Dataset, DisjointLoader, Graph, BatchLoader
from spektral.layers import GCSConv, GlobalAvgPool
from spektral.transforms.normalize_adj import NormalizeAdj

In [ ]:
#loading the dataset into keras compatible format


#All the graphs have same structure [Graph(n_nodes=3, n_node_features=4, n_edge_features=None, n_labels=1)]
#for i_3 in range(0,249):
 # print(dataset[i_3])  

 # We will use the batch loader because all molecules are of same structure

b_load = spektral.data.loaders.BatchLoader(dataset, mask=False, batch_size=2, epochs=None, shuffle=False, node_level=True)

In [ ]:
learning_rate = 1e-2  # Learning rate
epochs = 400  # Number of training epochs
es_patience = 10  # Patience for early stopping
batch_size = 1  # Batch size

In [ ]:
print(b_load)

b_load.batch_size

2

In [ ]:
idxs = np.random.permutation(len(dataset))
split_va, split_te = int(0.8 * len(dataset)), int(0.9 * len(dataset))
idx_tr, idx_va, idx_te = np.split(idxs, [split_va, split_te])
data_tr = dataset[idx_tr]
data_va = dataset[idx_va]
data_te = dataset[idx_te]

In [ ]:
loader_tr = BatchLoader(data_tr, batch_size=batch_size, epochs=epochs)
loader_va = DisjointLoader(data_va, batch_size=batch_size)
loader_te = DisjointLoader(data_te, batch_size=batch_size)

In [ ]:
class Net(Model):
    def __init__(self):
        super().__init__()
        self.conv1 = GCSConv(32, activation="relu")
        self.conv2 = GCSConv(32, activation="relu")
        self.conv3 = GCSConv(32, activation="relu")
        self.global_pool = GlobalAvgPool()
        self.dense = Dense(dataset.n_labels, activation="softmax")

    def call(self, inputs):
        x, a, i = inputs
        x = self.conv1([x, a])
        x = self.conv2([x, a])
        x = self.conv3([x, a])
        output = self.global_pool([x, i])
        output = self.dense(output)

        return output



In [ ]:
model = Net()
optimizer = Adam(lr=learning_rate)
loss_fn = CategoricalCrossentropy()

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
#Fitting/training the model

@tf.function(input_signature=loader_tr.tf_signature(), experimental_relax_shapes=True)
def train_step(inputs, target):
    with tf.GradientTape() as tape:
        predictions = model(inputs, training=True)
        loss = loss_fn(target, predictions) + sum(model.losses)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    acc = tf.reduce_mean(categorical_accuracy(target, predictions))
    return loss, acc


def evaluate(loader):
    output = []
    step = 0
    while step < loader.steps_per_epoch:
        step += 1
        inputs, target = loader.__next__()
        pred = model(inputs, training=False)
        outs = (
            loss_fn(target, pred),
            tf.reduce_mean(categorical_accuracy(target, pred)),
            len(target),  # Keep track of batch size
        )
        output.append(outs)
        if step == loader.steps_per_epoch:
            output = np.array(output)
            return np.average(output[:, :-1], 0, weights=output[:, -1])

epoch = step = 0
best_val_loss = np.inf
best_weights = None
patience = es_patience
results = []            

In [ ]:
for batch in b_load:
    step += 1
    loss, acc = train_step(*batch)
    results.append((loss, acc))
    if step == loader_tr.steps_per_epoch:
        step = 0
        epoch += 1

        # Compute validation loss and accuracy
        val_loss, val_acc = evaluate(loader_va)
        print(
            "Ep. {} - Loss: {:.3f} - Acc: {:.3f} - Val loss: {:.3f} - Val acc: {:.3f}".format(
                epoch, *np.mean(results, 0), val_loss, val_acc
            )
        )



IndexError: ignored

In [ ]:
b_load[0]

TypeError: ignored

In [ ]:
for q in range(1,100):
  Create_graph(q)

In [ ]:
def read(self):
    # We must return a list of Graph objects
    output = []

    for i in range(5):
        data = np.load(os.path.join(self.path, f'graph_{i}.npz'))
        output.append(
            Graph(x=data['x'], a=data['a'], y=data['y'])
        )

    return output

In [ ]:
print(MyDataset.n_labels)

In [ ]:
spektral.data.loaders.BatchLoader(MyDataset, mask=False, batch_size=1, epochs=None, shuffle=True, node_level=False)

In [ ]:
from spektral.data import BatchLoader
from spektral.models import GeneralGNN

loader = BatchLoader(MyDataset, batch_size=2)



In [ ]:
data = MyDataset(5, transforms=NormalizeAdj())

In [ ]:
def train_step(inputs, target):
    with tf.GradientTape() as tape:
        predictions = model(inputs, training=True)
        loss = loss_fn(target, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

In [ ]:
for batch in loader:
    train_step(*batch)

In [ ]:
class Net(Model):
    def __init__(self):
        super().__init__()
        self.conv1 = GCSConv(32, activation="relu")
        self.conv2 = GCSConv(32, activation="relu")
        self.conv3 = GCSConv(32, activation="relu")
        self.global_pool = GlobalAvgPool()
        self.dense = Dense(data.n_labels, activation="softmax")

    def call(self, inputs):
        x, a, i = inputs
        x = self.conv1([x, a])
        x = self.conv2([x, a])
        x = self.conv3([x, a])
        output = self.global_pool([x, i])
        output = self.dense(output)

        return output